/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: bigint;
    name: string;
    description: string;
    price: bigint;
}
export interface Contract {
    id: bigint;
    model: string;
    clientId: bigint;
    endDate: string;
    productName: string;
    details: string;
    quantity: bigint;
    price: bigint;
    remarks: string;
    startDate: string;
}
export interface Invoice {
    id: bigint;
    clientId: bigint;
    date: string;
    number: string;
    amount: bigint;
}
export interface FinancialRecord {
    id: bigint;
    transactionDetails: string;
    recordType: string;
    amount: bigint;
}
export interface Customer {
    id: bigint;
    contactInfo: string;
    name: string;
    company: string;
}
export interface FinancialSummary {
    balance: bigint;
    totalIncome: bigint;
    totalExpenses: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createContract(contract: Contract): Promise<void>;
    createCustomer(customer: Customer): Promise<void>;
    createFinancialRecord(record: FinancialRecord): Promise<void>;
    createInvoice(invoice: Invoice): Promise<void>;
    createProduct(product: Product): Promise<void>;
    deleteContract(id: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteFinancialRecord(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    getAllContracts(): Promise<Array<Contract>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllFinancialRecords(): Promise<Array<FinancialRecord>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContract(id: bigint): Promise<Contract | null>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getFinancialRecord(id: bigint): Promise<FinancialRecord | null>;
    getFinancialSummary(): Promise<FinancialSummary>;
    getInvoice(id: bigint): Promise<Invoice | null>;
    getProduct(id: bigint): Promise<Product | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateContract(contract: Contract): Promise<void>;
    updateCustomer(customer: Customer): Promise<void>;
    updateFinancialRecord(record: FinancialRecord): Promise<void>;
    updateInvoice(invoice: Invoice): Promise<void>;
    updateProduct(product: Product): Promise<void>;
}
import type { Contract as _Contract, Customer as _Customer, FinancialRecord as _FinancialRecord, Invoice as _Invoice, Product as _Product, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createContract(arg0: Contract): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0);
            return result;
        }
    }
    async createCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0);
            return result;
        }
    }
    async createFinancialRecord(arg0: FinancialRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinancialRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinancialRecord(arg0);
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0);
            return result;
        }
    }
    async createProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async deleteContract(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContract(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteFinancialRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinancialRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinancialRecord(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContracts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContracts();
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllFinancialRecords(): Promise<Array<FinancialRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFinancialRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFinancialRecords();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getContract(arg0: bigint): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContract(arg0);
                return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContract(arg0);
            return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFinancialRecord(arg0: bigint): Promise<FinancialRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialRecord(arg0);
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialRecord(arg0);
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFinancialSummary(): Promise<FinancialSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialSummary();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n9(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n9(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateContract(arg0: Contract): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContract(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0);
            return result;
        }
    }
    async updateFinancialRecord(arg0: FinancialRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinancialRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinancialRecord(arg0);
            return result;
        }
    }
    async updateInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0);
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contract]): Contract | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FinancialRecord]): FinancialRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}