/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'model' : IDL.Text,
  'clientId' : IDL.Nat,
  'endDate' : IDL.Text,
  'productName' : IDL.Text,
  'details' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'remarks' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'company' : IDL.Text,
});
export const FinancialRecord = IDL.Record({
  'id' : IDL.Nat,
  'transactionDetails' : IDL.Text,
  'recordType' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'clientId' : IDL.Nat,
  'date' : IDL.Text,
  'number' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FinancialSummary = IDL.Record({
  'balance' : IDL.Int,
  'totalIncome' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createContract' : IDL.Func([Contract], [], []),
  'createCustomer' : IDL.Func([Customer], [], []),
  'createFinancialRecord' : IDL.Func([FinancialRecord], [], []),
  'createInvoice' : IDL.Func([Invoice], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'deleteContract' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteFinancialRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllFinancialRecords' : IDL.Func(
      [],
      [IDL.Vec(FinancialRecord)],
      ['query'],
    ),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContract' : IDL.Func([IDL.Nat], [IDL.Opt(Contract)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getFinancialRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(FinancialRecord)],
      ['query'],
    ),
  'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContract' : IDL.Func([Contract], [], []),
  'updateCustomer' : IDL.Func([Customer], [], []),
  'updateFinancialRecord' : IDL.Func([FinancialRecord], [], []),
  'updateInvoice' : IDL.Func([Invoice], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'model' : IDL.Text,
    'clientId' : IDL.Nat,
    'endDate' : IDL.Text,
    'productName' : IDL.Text,
    'details' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'remarks' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'company' : IDL.Text,
  });
  const FinancialRecord = IDL.Record({
    'id' : IDL.Nat,
    'transactionDetails' : IDL.Text,
    'recordType' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'clientId' : IDL.Nat,
    'date' : IDL.Text,
    'number' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FinancialSummary = IDL.Record({
    'balance' : IDL.Int,
    'totalIncome' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createContract' : IDL.Func([Contract], [], []),
    'createCustomer' : IDL.Func([Customer], [], []),
    'createFinancialRecord' : IDL.Func([FinancialRecord], [], []),
    'createInvoice' : IDL.Func([Invoice], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'deleteContract' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteFinancialRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllFinancialRecords' : IDL.Func(
        [],
        [IDL.Vec(FinancialRecord)],
        ['query'],
      ),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContract' : IDL.Func([IDL.Nat], [IDL.Opt(Contract)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getFinancialRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(FinancialRecord)],
        ['query'],
      ),
    'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContract' : IDL.Func([Contract], [], []),
    'updateCustomer' : IDL.Func([Customer], [], []),
    'updateFinancialRecord' : IDL.Func([FinancialRecord], [], []),
    'updateInvoice' : IDL.Func([Invoice], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };