/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contract {
  'id' : bigint,
  'model' : string,
  'clientId' : bigint,
  'endDate' : string,
  'productName' : string,
  'details' : string,
  'quantity' : bigint,
  'price' : bigint,
  'remarks' : string,
  'startDate' : string,
}
export interface Customer {
  'id' : bigint,
  'contactInfo' : string,
  'name' : string,
  'company' : string,
}
export interface FinancialRecord {
  'id' : bigint,
  'transactionDetails' : string,
  'recordType' : string,
  'amount' : bigint,
}
export interface FinancialSummary {
  'balance' : bigint,
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
}
export interface Invoice {
  'id' : bigint,
  'clientId' : bigint,
  'date' : string,
  'number' : string,
  'amount' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContract' : ActorMethod<[Contract], undefined>,
  'createCustomer' : ActorMethod<[Customer], undefined>,
  'createFinancialRecord' : ActorMethod<[FinancialRecord], undefined>,
  'createInvoice' : ActorMethod<[Invoice], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'deleteContract' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteFinancialRecord' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllContracts' : ActorMethod<[], Array<Contract>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllFinancialRecords' : ActorMethod<[], Array<FinancialRecord>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContract' : ActorMethod<[bigint], [] | [Contract]>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getFinancialRecord' : ActorMethod<[bigint], [] | [FinancialRecord]>,
  'getFinancialSummary' : ActorMethod<[], FinancialSummary>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateContract' : ActorMethod<[Contract], undefined>,
  'updateCustomer' : ActorMethod<[Customer], undefined>,
  'updateFinancialRecord' : ActorMethod<[FinancialRecord], undefined>,
  'updateInvoice' : ActorMethod<[Invoice], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];